<a href="https://colab.research.google.com/github/Yaroslav-Maloshuk/Numerical_Analysis/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B0_4_1_%D0%9C%D0%B0%D0%BB%D0%BE%D1%88%D1%83%D0%BA_%D0%AF%D1%80%D0%BE%D1%81%D0%BB%D0%B0%D0%B2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Малошук Ярослав
ФІТ 2-15

In [50]:
import numpy as np
np.__version__

'2.0.2'

1.Створи матрицю 3*3, заповни її цілими випадковими числами від 1 до 5

In [51]:
matrix = np.random.randint(1, 6, size=(3, 3))
matrix

array([[2, 5, 4],
       [1, 4, 3],
       [1, 2, 5]])

2.Обчислити визначник матриці

In [52]:
det = np.linalg.det(matrix)
det

np.float64(9.999999999999998)

3.Знайти добуток всіх елементів матриці

In [53]:
product = np.prod(matrix)
product

np.int64(4800)

In [56]:
prod_1 = np.prod(matrix[0])
prod_1

np.int64(40)

In [57]:
prod_2 = np.prod(matrix[1])
prod_2

np.int64(12)

In [58]:
prod_3 = np.prod(matrix[2])
prod_3

np.int64(10)

In [59]:
prod_1 * prod_2 * prod_3

np.int64(4800)

4.Знайти суму всіх елементів матриці

In [60]:
sum = np.sum(matrix)
sum

np.int64(27)

5.Обчислити найбільший, найменший елементи

In [61]:
max_element = np.max(matrix)
max_element

np.int64(5)

In [62]:
min_element = np.min(matrix)
min_element

np.int64(1)

6.Знайти середнє значення елементів матриці

In [63]:
mean = np.mean(matrix)
mean

np.float64(3.0)

7.Знайти матрицю, що складена з квадратних коренів

In [64]:
sqrt_matrix = np.sqrt(matrix)
sqrt_matrix

array([[1.41421356, 2.23606798, 2.        ],
       [1.        , 2.        , 1.73205081],
       [1.        , 1.41421356, 2.23606798]])

8.Обчислити суму елементів кожного рядка. Відповідь записати як вектор-стовпчик

In [65]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)
row_sums

array([[11],
       [ 8],
       [ 8]])

9.Створити вектор, що містить 25 елементів. Заповнити числами від 0 до 9. Відсортувати числа за спаданням.

In [66]:
vector = np.random.randint(0, 10, size=25)
vector

array([5, 1, 7, 7, 0, 5, 6, 1, 0, 2, 2, 5, 0, 9, 7, 5, 6, 3, 3, 1, 7, 0,
       3, 5, 7])

In [67]:
sorted_vector = np.sort(vector)[::-1]
sorted_vector

array([9, 7, 7, 7, 7, 7, 6, 6, 5, 5, 5, 5, 5, 3, 3, 3, 2, 2, 1, 1, 1, 0,
       0, 0, 0])

10.Знайти моду, медіану, середнє, максимальне, мінімальне значення

In [68]:
from scipy import stats

In [69]:
mode = stats.mode(vector)
mode

ModeResult(mode=np.int64(5), count=np.int64(5))

In [70]:
median = np.median(vector)
median

np.float64(5.0)

In [71]:
mean = np.mean(vector)
mean

np.float64(3.88)

In [72]:
max_value = np.max(vector)
max_value

np.int64(9)

In [73]:
min_value = np.min(vector)
min_value

np.int64(0)

11.Створити дві матриці 4*4, заповнені числами від 1 до 10. Обчислити суму, різницю, поелементний добуток, частку.

In [74]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix1

array([[ 3,  9,  2,  6],
       [ 7,  7,  3,  5],
       [10,  5,  2,  5],
       [ 8,  2,  6,  7]])

In [75]:
matrix2 = np.random.randint(1, 11, size=(4, 4))
matrix2

array([[ 2,  3,  3,  7],
       [10,  2,  1,  6],
       [ 7,  6,  8,  7],
       [ 7,  9,  7,  8]])

In [76]:
matrix_sum = matrix1 + matrix2
matrix_sum

array([[ 5, 12,  5, 13],
       [17,  9,  4, 11],
       [17, 11, 10, 12],
       [15, 11, 13, 15]])

In [77]:
matrix_diff = matrix1 - matrix2
matrix_diff

array([[ 1,  6, -1, -1],
       [-3,  5,  2, -1],
       [ 3, -1, -6, -2],
       [ 1, -7, -1, -1]])

In [78]:
matrix_product = matrix1 * matrix2
matrix_product

array([[ 6, 27,  6, 42],
       [70, 14,  3, 30],
       [70, 30, 16, 35],
       [56, 18, 42, 56]])

In [79]:
matrix_division = np.divide(matrix1, matrix2, where=(matrix2 != 0))
matrix_division

array([[1.5       , 3.        , 0.66666667, 0.85714286],
       [0.7       , 3.5       , 3.        , 0.83333333],
       [1.42857143, 0.83333333, 0.25      , 0.71428571],
       [1.14285714, 0.22222222, 0.85714286, 0.875     ]])

12.Задати вектор-рядок, що містить дійсні числа 0-8.0. Зробити матрицю 3*3. Помножити на вектор-рядок, що містить числа 0-2.0.

In [80]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [81]:
x1 = x.reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [82]:
x2 = np.arange(3.0)
x2

array([0., 1., 2.])

In [83]:
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

13.Задати вектор-рядок (числа 1-5). Обчислити вектор в кубі.

In [84]:
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [85]:
np.power(x1, 3)

array([  0,   1,   8,  27,  64, 125])

14. Піднести до ступеня

In [86]:
x2 = np.array([1, 2, 3, 3, 2, 1])
x2

array([1, 2, 3, 3, 2, 1])

In [87]:
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [88]:
x1 ** x2

array([ 0,  1,  8, 27, 16,  5])

Висновок: Навчились працювати з матрицями, визначниками, векторами та операціями над матрицями за допомогою мови Python та його бібліотек numpy і scipy.